language: php
dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0
    - COMPOSER_MEMORY_LIMIT=-1

jobs:
  include:
    - stage: test
      php: 5.6
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/security-checker security:check

    - stage: test
      php: 7.0
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/security-checker security:check

    - stage: test
      php: 7.1
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/security-checker security:check

    - stage: test
      php: 7.2
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/security-checker security:check

    # PHP-CS-Fixer is not yet compatible with PHP 7.3
    - stage: test
      php: 7.3
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --ignore-platform-reqs --no-interaction --no-suggest
      script:
        - php vendor/bin/security-checker security:check

  allow_failures:
    - php: nightly
